name: Local Ollama
version: 1.0.0
schema: v1

models:
  - name: Qwen Coder
    provider: ollama
    model: qwen2.5-coder:3b
    roles:
      - chat
      - edit
      - apply
      - autocomplete

defaultModel: Qwen Coder